### ISSUE TITLE
whatwg's commit list outside of  DOM 4.1 Working Draft

### ISSUE THREAD

**Issue by wucongdonglai** [w3c/dom#15]
We are working on the DOM 4.1 Working Draft. We compared all the different commits between w3c/dom gh-pages branch and whatwg/dom master branch in this [compare link](https://github.com/w3c/dom/compare/gh-pages...whatwg:master) .
As the analysed result of all the commits, we'll take the following commits outside of the working draft, which means these commits won't be included in DOM 4.1 Working Draft.
The commit list is as follow:
 - [ ]  https://github.com/whatwg/dom/commit/fb45d52 Fix #115: add getAttributeNames()
 - [ ]  https://github.com/whatwg/dom/commit/7b5e052 Fix #115 (again): clarify that getAttributeNames() can return the emp  
 - [ ]  https://github.com/whatwg/dom/commit/e012ffe Make it clear getElementsByTagName operates on descendants  
 - [ ]  https://github.com/whatwg/dom/commit/b58cf9b Consistify
 - [ ]  https://github.com/whatwg/dom/commit/908ca06 Point out where tests can be found
 - [ ]  https://github.com/whatwg/dom/commit/7fd852a Fix #143: make getElementsByTagName match on qualified name
 - [ ]  https://github.com/whatwg/dom/commit/62e332b Close #152: keep new bikeshed from changing these IDs
 - [ ]  https://github.com/whatwg/dom/commit/7613431 Close #154: fix typo
 - [ ]  https://github.com/whatwg/dom/commit/07e9fc0 Fix #119: merge DOMSettableTokenList into DOMTokenList  
 - [ ]  https://github.com/whatwg/dom/commit/1c2017f Fix typo
 - [ ]  https://github.com/whatwg/dom/commit/dfbb0b8 Fix a typo  
 - [ ]  https://github.com/whatwg/dom/commit/2d7b637 Integrate HTML's monkey patch to the event path  
 - [ ]  https://github.com/whatwg/dom/commit/5a20a8f Editorial: Adjust syntax for NonElementParentNode & ParentNode headers  
 - [ ]  https://github.com/whatwg/dom/commit/02ec9c7 Make cloneNode() throw for ShadowRoot objects  
 - [ ]  https://github.com/whatwg/dom/commit/742e8c1 Use [LegacyUnenumerableNamedProperties]
 - [ ]  https://github.com/whatwg/dom/commit/2cccaf9 Editorial: an affect => an effect  
 - [ ]  https://github.com/whatwg/dom/commit/09d7eb6 Fix #148: drop "keyevents" as an alias of "keyboardevent" for createE  
 - [ ]  https://github.com/whatwg/dom/commit/09cf3ae Mention the code of conduct and contribution opportunities in the README
 - [ ]  https://github.com/whatwg/dom/commit/a71b88d Cross-reference "get the parent"  
 - [ ]  https://github.com/whatwg/dom/commit/0316b62 Add Node.prototype.rootNode  
 - [ ]  https://github.com/whatwg/dom/commit/97f0a95 Restore Node.prototype.isSameNode()  
 - [ ]  https://github.com/whatwg/dom/commit/25d680d Editorial: swap order of DocumentType and DocumentFragment
 - [ ]  https://github.com/whatwg/dom/commit/b2ee400 Shadow: add shadow root  
 - [ ]  https://github.com/whatwg/dom/commit/1699495 Shadow: define .attachShadow() and .shadowRoot
 - [ ]  https://github.com/whatwg/dom/commit/db1362f Editorial: rename interface to mixin  
 - [ ]  https://github.com/whatwg/dom/commit/4183385 Shadow: add DocumentOrShadowRoot mixin  
 - [ ]  https://github.com/whatwg/dom/commit/2d5aaed Shadow: run insertion and removing steps also for shadow trees  
 - [ ]  https://github.com/whatwg/dom/commit/e41d91c Editorial: add missing paranthesis  
 - [ ]  https://github.com/whatwg/dom/commit/b4cc543 Editorial: shadow-including rather than shadow-root-including  
 - [ ]  https://github.com/whatwg/dom/commit/25b6110 Shadow: include shadow trees when adopting  
 - [ ]  https://github.com/whatwg/dom/commit/c7ec95d Editorial: define "in a document" better
 - [ ]  https://github.com/whatwg/dom/commit/018440e Editorial: add sections on document and shadow trees
 - [ ]  https://github.com/whatwg/dom/commit/ce7df0b Editorial: be clearer on host, define light tree
 - [ ]  https://github.com/whatwg/dom/commit/150147a Editorial: root references require a for attribute  
 - [ ]  https://github.com/whatwg/dom/commit/a2b04df Shadow: define slots and slotables
 - [ ]  https://github.com/whatwg/dom/commit/b8e1ccf Shadow: define assignedSlot of Element and Text
 - [ ]  https://github.com/whatwg/dom/commit/810cce8 Shadow: add ShadowRoot's mode attribute  
 - [ ]  https://github.com/whatwg/dom/commit/e3d8291 Shadow: define superglobal slot content attribute  
 - [ ]  https://github.com/whatwg/dom/commit/e996bdc Editorial: mention that step="" conformance requirements are out of s  
 - [ ]  https://github.com/whatwg/dom/commit/7dae99c Editorial: define in a shadow-including document and shadow-including  
 - [ ]  https://github.com/whatwg/dom/commit/76fbe55 Shadow: fix shadow-including root  
 - [ ]  https://github.com/whatwg/dom/commit/ce331fd Restore getAttributeNS()  
 - [ ]  https://github.com/whatwg/dom/commit/6b06d0b Editorial: cleanup for NamedNodeMap
 - [ ]  https://github.com/whatwg/dom/commit/b9b9fe1 Introducing node.isConnected  
 - [ ]  https://github.com/whatwg/dom/commit/cd643f8 Align spelling of Unscopable with IDL and JavaScript  
 - [ ]  https://github.com/whatwg/dom/commit/7f63535 Add support for custom elements  
 - [ ]  https://github.com/whatwg/dom/commit/1784903 Meta: improve pull request instructions for DOM  
 - [ ]  https://github.com/whatwg/dom/commit/b8d2854 Shadow: define attachShadow() for custom elements
 - [ ]  https://github.com/whatwg/dom/commit/9b8612a Meta: make it easier to reference participate in a tree  
 - [ ]  https://github.com/whatwg/dom/commit/81566a3 Shadow: define slotchange event  
 - [ ]  https://github.com/whatwg/dom/commit/3536dd9 Editorial: update custom element cross-spec references
 - [ ]  https://github.com/whatwg/dom/commit/a878733 Editorial: fix a few cross-linking missteps
 - [ ]  https://github.com/whatwg/dom/commit/5fc5624 Editorial: make "is" and "prefix" optional in "create an element"
 - [ ]  https://github.com/whatwg/dom/commit/7b42a54 Use "create an element" in createHTMLDocument  
 - [ ]  https://github.com/whatwg/dom/commit/9c00ee2 Editorial: introduce more shadow-including terms for CSS  
 - [ ]  https://github.com/whatwg/dom/commit/e35b570 Editorial: distributed -> flattened
 - [ ]  https://github.com/whatwg/dom/commit/d4d27a6 Meta: export more terms  
 - [ ]  https://github.com/whatwg/dom/commit/8ae8749 Editorial: add "shadow host" and "assigned" as terms  
 - [ ]  https://github.com/whatwg/dom/commit/8d281a3 Editorial: flip non-null
 - [ ]  https://github.com/whatwg/dom/commit/fdad8cb Shadow: <slot> is now defined in HTML
 - [ ]  https://github.com/whatwg/dom/commit/0f08850 Meta: point out event's timeStamp is likely to change  
 - [ ]  https://github.com/whatwg/dom/commit/a77a920 Editorial: deduplicate Veli Şenol
 - [ ]  https://github.com/whatwg/dom/commit/e4f904f Meta: link to Japanese translation  
 - [ ]  https://github.com/whatwg/dom/commit/ed94c9f Shadow: define event retargeting for shadow trees  
 - [ ]  https://github.com/whatwg/dom/commit/28689ed Editorial: add <code> back to the Events section
 - [ ]  https://github.com/whatwg/dom/commit/1e6df2b Editorial: fix markup typo
 - [ ]  https://github.com/whatwg/dom/commit/6e1b038 Rename scoped to composed and invert its meaning  
 - [ ]  https://github.com/whatwg/dom/commit/58b19e4 Shadow: define Event's composedPath()  
 - [ ]  https://github.com/whatwg/dom/commit/ce21cb5 Shadow: update the definition of an unclosed node  
 - [ ]  https://github.com/whatwg/dom/commit/d077da1 Don't set custom element state redundantly  
 - [ ]  https://github.com/whatwg/dom/commit/e417f9f Un-customify adopted elements  
 - [ ]  https://github.com/whatwg/dom/commit/754bb8d Save the is="" value an element was created with  
 - [ ]  https://github.com/whatwg/dom/commit/42a45eb Remove Node.prototype.rootNode  
 - [ ]  https://github.com/whatwg/dom/commit/00250fc Fix example of "undefined" custom element state  
 - [ ]  https://github.com/whatwg/dom/commit/579ef07 Add Node.prototype.getRootNode()  
 - [ ]  https://github.com/whatwg/dom/commit/11725ec Meta: add advice on using the Bikeshed HTTP API  
 - [ ]  https://github.com/whatwg/dom/commit/970d750 Rename "in a (shadow-including) document"  
 - [ ]  https://github.com/whatwg/dom/commit/539e452 Set the stage for preventing double custom element constructor calls  
 - [ ]  https://github.com/whatwg/dom/commit/ef69a24 Shadow: define event's relatedTarget handling  
 - [ ]  https://github.com/whatwg/dom/commit/fbc0c31 Shadow: add "retargeting steps" to the dispatch algorithm  
 - [ ]  https://github.com/whatwg/dom/commit/443023a Editorial: stop enumerating ShadowRoot alongside DocumentFragment  
 - [ ]  https://github.com/whatwg/dom/commit/ca0f853 Shadow: rename "unclosed node"  
 - [ ]  https://github.com/whatwg/dom/commit/c46a4ad Editorial: fix typo in public-script-coord spelling  
 - [ ]  https://github.com/whatwg/dom/commit/2153769 Shadow: adjust composedPath() when currentTarget is a Window object  
 - [ ]  https://github.com/whatwg/dom/commit/17f5118 Editorial: wholeText is not a method  
 - [ ]  https://github.com/whatwg/dom/commit/afac504 Shadow: do not dispatch an event when target is reletedTarget  
 - [ ]  https://github.com/whatwg/dom/commit/b3571d7 Shadow: safelist "main" in attachShadowRoot()  
 - [ ]  https://github.com/whatwg/dom/commit/89a849a Shadow: stop re-signaling a slotchange event  
 - [ ]  https://github.com/whatwg/dom/commit/aef3ea4 Meta: set up the architecture for commit
 - [ ]  https://github.com/whatwg/dom/commit/8eb68e4 Meta: minor commit snapshot cleanup  
 - [ ]  https://github.com/whatwg/dom/commit/80b1640 Drop support for SVGZoomEvent in createEvent()  
 - [ ]  https://github.com/whatwg/dom/commit/766a5e7 Remove incorrect customized built-in element checks  
 - [ ]  https://github.com/whatwg/dom/commit/bb2890b Editorial: make use of the Infra Standard
 - [ ]  https://github.com/whatwg/dom/commit/46fac22 Meta: fix markup errors
 - [ ]  https://github.com/whatwg/dom/commit/3f8b236 xref
 - [ ]  https://github.com/whatwg/dom/commit/32e8fb8 cleanup
 - [ ]  https://github.com/whatwg/dom/commit/d2bf0a9 Make subresources work
 - [ ]  https://github.com/whatwg/dom/commit/f63b2ee CC0 TLS
 - [ ]  https://github.com/whatwg/dom/commit/2d9f7f3 Moar TLS
 - [ ]  https://github.com/whatwg/dom/commit/d9d7193 Align Acknowledgments with URL and Encoding
 - [ ]  https://github.com/whatwg/dom/commit/26a792e Turns out nobody filed bugs for all these error names. And since IDL   
 - [ ]  https://github.com/whatwg/dom/commit/b43b578 Less boilerplate in the heading
 - [ ]  https://github.com/whatwg/dom/commit/af1286e Add README.md
 - [ ]  https://github.com/whatwg/dom/commit/2420bae Always use the HTTPS URL for bugzilla.  
 - [ ]  https://github.com/whatwg/dom/commit/9f0d812 typo
 - [ ]  https://github.com/whatwg/dom/commit/1e2535f xref; fixes whatwg#13
 - [ ]  https://github.com/whatwg/dom/commit/b2eb25f Mark new APIs as [Unscopeable] https:
 - [ ]  https://github.com/whatwg/dom/commit/50c63c3 typo https:
 - [ ]  https://github.com/whatwg/dom/commit/d08e68f Convert to Bikeshed.
 - [ ]  https://github.com/whatwg/dom/commit/b105abe Reorganize the repository given the shift to bikeshed
 - [ ]  https://github.com/whatwg/dom/commit/1de425f More HTTPS, restore header.
 - [ ]  https://github.com/whatwg/dom/commit/c7784f8 Fix the header, #21
 - [ ]  https://github.com/whatwg/dom/commit/b2a0537 Sync with Bikeshed
 - [ ]  https://github.com/whatwg/dom/commit/b931e3d Remove {{ }} from output. Fixes #22
 - [ ]  https://github.com/whatwg/dom/commit/0a87261 Export all the terms in the spec, and fix a few definitions
 - [ ]  https://github.com/whatwg/dom/commit/c3d7ce0 Add a common conjugation of case-sensitive for use by CSS. Also indic  
 - [ ]  https://github.com/whatwg/dom/commit/27b9b3c Fix the ID for DOMImplementation (was #interface=domimplementation)
 - [ ]  https://github.com/whatwg/dom/commit/a00a03b Bikeshed update. This fixes fragment identifiers all over. And should  
 - [ ]  https://github.com/whatwg/dom/commit/04bc94b Forgot to ack @samgiles for the previous commit. Yay for community co  
 - [ ]  https://github.com/whatwg/dom/commit/04b1837 Minor rewording of non-normative addEventListener() text.
 - [ ]  https://github.com/whatwg/dom/commit/5c10bf4 Fix typo in id #firint-vents -> #firing-events. Closes #51.
 - [ ]  https://github.com/whatwg/dom/commit/96ef454 Clarify statement about Elements. Fixes https:
 - [ ]  https://github.com/whatwg/dom/commit/cc5db00 Tidy up language around hasFeature().
 - [ ]  https://github.com/whatwg/dom/commit/c21b79e Note cleanup and removing bikeshed warnings.
 - [ ]  https://github.com/whatwg/dom/commit/07e859a New Bikeshed serializer
 - [ ]  https://github.com/whatwg/dom/commit/2a9a923 Fix #65: restore spaces in serialized output
 - [ ]  https://github.com/whatwg/dom/commit/a923241 Fix #73: createEvent() no longer linked to Event's constructor defini  
 - [ ]  https://github.com/whatwg/dom/commit/c09e1b4 Some variables are unique snowflakes
 - [ ]  https://github.com/whatwg/dom/commit/27b1696 Close #95: lowercase all IDs  
 - [ ]  https://github.com/whatwg/dom/commit/3a5e18a Close #100: lowercase more IDs
 - [ ]  https://github.com/whatwg/dom/commit/a4449e5 Close #101: add some manual dfns to Elements  
 - [ ]  https://github.com/whatwg/dom/commit/55169f6 Include more PR instructions
 - [ ]  https://github.com/whatwg/dom/commit/5d8ecd7 Ack update per whatwg#81 (comment)
 - [ ]  https://github.com/whatwg/dom/commit/6bc1513 Fix #113: reword paragraph in DOM introduction

Any comment or discussion is welcome.

**Comment by yongsheng** [comment]
thanks, @wucongdonglai .

**Comment by zqzhang** [comment]
One more:

- [ ] https://github.com/whatwg/dom/commit/14e7c6e Address some xref issues

**Comment by yongsheng** [comment]
Several of fixes have been in DOM4.1. we need to review all of them one by one.

**Comment by xfq** [comment]
Can this issue be closed given we're heading toward DOM 4.2, @yongsheng?

**Comment by yongsheng** [comment]
yes, i'll close this and create new ones if we have issues.
