### ISSUE TITLE
Wide review tracker for DOM 4.1

### ISSUE THREAD

**Issue by xfq** [w3c/dom#172]
As a requirement for publishing a specification as a [Candidate Recommendation], the group:

> must show that the specification has received wide review

To satisfy this requirement, we use this tracker issue as an evidence that [wide review] from [horizontal groups] has been received.

Ref: [RfC Template]

### Horizontal groups

  * Wide review announcement
    * [x] Publish a pre-CR Working Draft used as a basis for wide review
    * [ ] Review request:
    * [ ] Feedback:
  * Technical Architecture Group
    * [ ] Review request:
    * [ ] Feedback:
  * Security
    * [ ] Work through the Security and Privacy Questionnaire
    * [ ] Review request:
    * [ ] Feedback:
  * Privacy
    * [ ] Work through the Security and Privacy Questionnaire
    * [ ] Review request:
    * [ ] Feedback:
  * Internationalization
    * [ ] Work through the [i18n Checklist]
    * [ ] Open a review request at https://github.com/w3c/i18n-activity/issues/
  * Accessibility
    * [ ] Work through the [a11y Questionnaire] and [a11y Checklist]
    * [ ] Send a review request to public-apa@w3.org

### Other groups

Other [W3C Groups] that have interactions with this work:

* CSS WG (for CSS-related aspects, like Shadow DOM and CSSOM)
   * [ ] Review request:
   * [ ] Feedback:

[Candidate Recommendation]: https://www.w3.org/2017/Process-20170301/#candidate-rec
[wide review]: https://www.w3.org/2017/Process-20170301/#wide-review
[horizontal groups]: https://www.w3.org/Guide/Charter.html#horizontal-review

[RfC Template]: https://www.w3.org/wiki/DocumentReview#Request_for_Comments_.28RfC.29_Template
[W3C Groups]: https://www.w3.org/2017/08/webplatform-charter.html#coordination
[i18n Checklist]: https://www.w3.org/International/techniques/developing-specs
[a11y Checklist]: https://w3c.github.io/apa/fast/checklist.html
[a11y Questionnaire]: https://github.com/stevefaulkner/accessibility-spec-questionnaire/blob/master/accessibility-spec-questionnaire.md

References:
* https://www.w3.org/2017/Process-20170301/#wide-review
* https://www.w3.org/wiki/DocumentReview

**Comment by xfq** [comment]
@chaals, below I drafted a proposal for the wide review announcement to be sent to public-review-announce@w3.org using the [RfC Template], please take a look:

```
Subject: RfC: wide review of DOM 4.1
To: public-review-announce@w3.org
Bcc: chairs@w3.org

Hi,

The Web Platform Working Group requests review of the following
specification before 2018-02-31:

   W3C DOM 4.1
   https://www.w3.org/TR/dom41/

The group requests feedback via the specification's GitHub
repository: https://github.com/w3c/dom/issues

This publication is a Pre-Candidate Recommendation Draft under the
2017 Process [1]. Therefore, the group is looking for confirmation
that it has satisfied its relevant technical requirements and
dependencies with other groups.

Thanks,

@@Chaals, or Fuqiao?@@

[1] https://www.w3.org/wiki/DocumentReview
```

Would you like to send the review requests, or do you want me to, @chaals?

[RfC Template]: https://www.w3.org/wiki/DocumentReview#Request_for_Comments_.28RfC.29_Template

**Comment by xfq** [comment]
I'll send them.

**Comment by xfq** [comment]
All wide review requests have now been sent.

**Comment by xfq** [comment]
The wide review period has ended.
