### ISSUE TITLE
Mutation Algorithms: mistakes in replacing a node

### ISSUE THREAD

**Issue by yongsheng** [w3c/dom#25]
- [ ] https://github.com/whatwg/dom/commit/f2b2a22 Close #128: fix a typo in the replace a node algorithm
- [ ] https://github.com/whatwg/dom/commit/cfaf3fa Fix #129: error in replace algorithm
- [ ] https://github.com/whatwg/dom/commit/9c26c6d Close #138: fix a typo in the replace algorithm
- [ ] https://github.com/whatwg/dom/commit/1b9e2f9 Need to grab children of a DocumentFragment before an insert.
- [ ] https://github.com/whatwg/dom/commit/d9fbd12 Replacing a child within parent had the wrong previousSibling in its mutation record Fixes #59 
- [ ] https://github.com/whatwg/dom/commit/5aecfd4 Since node can be child, record the previous sibling before adopting Fixes #59 (again).
- [ ] https://github.com/whatwg/dom/commit/c20e4b5 Do not remove child from its parent when replacing a node by itself

**Comment by yongsheng** [comment]
related to #82 .
